### ISSUE TITLE
Imcompatible disclosure license

### ISSUE THREAD

**Issue by 0xae** [NOSiCode-CV/IGRP-Framework#107]
## welcome to github IGRP team
i hope we can work together and make cape verde IT economy flourish

it seems to me your project uses GPL, which grants permissions for "Commercial use" , see [link](https://github.com/NOSiCode-CV/IGRP-Framework/blob/master/LICENSE.md).
so effectively it nullifies this "É vedado qualquer uso do código fonte para fins diferentes dos autorizados neste aviso, nomeadamente para uso comercial. " .

what do you think?

**Comment by natalio** [comment]
Tinha reparado essa incompatibilidade
Espero que corrijam então essa licença

**Comment by IMarcelF** [comment]
Oops !!!

De fato, verifica-se uma inconsistência entre a licença (GNU GPL) aplicada e o disclaimer (definido no README.MD). Neste momento, estamos a trabalhar a questão da licença com o objectivo de determinar a melhor solução possível à aplicar.

Agradecemos e muito os comentários feitos sobre o assunto ... Em breve será definido uma licença ...

Também estamos a trabalhar sobre a documentação da plataforma (em breve estará disponível em [nosicode](http://www.nosicode.cv/index.php)), as premiações e os certificados que serão atribuídos à aqueles cuja as contribuições serão uma mais valia para o IGRP, porque trabalhando juntos ... faremos de Cabo Verde uma referência extraordinária e de nível mundial no mundo de IT. 

Atentamente ... Graciás !

**Comment by cnlc** [comment]
Agradeciamos a definição da licença o quanto antes de modo a evitar constrangimentos futuros.
Se pudessem publicar a documentação sobre o deploy seria uma mais valia.

**Comment by 0xae** [comment]
@cnlc parece ser parte da documentacao da plataforma.
quanto a licenca acho que estao preocupados em preservar o direito intelectual e me parece que
querem limitar o aspecto comercial,o que leva para longe mais developers que poderiam contribuir com isso, but hey, they can still change their minds ;) 
also, parece ser o quao muito apenas uma aplicacao war normal.
