### ISSUE TITLE
Edit fields

### ISSUE THREAD

**Issue by DocantoG** [NOSiCode-CV/IGRP-Framework#1797]
![image](https://github.com/NOSiCode-CV/IGRP-Framework/assets/140892502/4c03f9ee-3e16-4c3c-b2d2-2ae1a17022c8)

**Comment by NOSiopen** [comment]
BugFix in v.2.0.0.231108 released internally in sonatype.nosi.cv

<img width="282" alt="image" src="https://github.com/NOSiCode-CV/IGRP-Framework/assets/28312206/0db631c2-7191-4cd0-bacb-077acc4eab61">
